set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[0]}]

set_property PACKAGE_PIN C19 [get_ports {seg_en[0]}]
set_property PACKAGE_PIN E19 [get_ports {seg_en[1]}]
set_property PACKAGE_PIN D19 [get_ports {seg_en[2]}]
set_property PACKAGE_PIN F18 [get_ports {seg_en[3]}]
set_property PACKAGE_PIN E18 [get_ports {seg_en[4]}]
set_property PACKAGE_PIN B20 [get_ports {seg_en[5]}]
set_property PACKAGE_PIN A20 [get_ports {seg_en[6]}]
set_property PACKAGE_PIN A18 [get_ports {seg_en[7]}]


set_property PACKAGE_PIN F15 [get_ports {seg_out[0]}]
set_property PACKAGE_PIN F13 [get_ports {seg_out[1]}]
set_property PACKAGE_PIN F14 [get_ports {seg_out[2]}]
set_property PACKAGE_PIN F16 [get_ports {seg_out[3]}]

set_property PACKAGE_PIN E17 [get_ports {seg_out[4]}]
set_property PACKAGE_PIN C14 [get_ports {seg_out[5]}]
set_property PACKAGE_PIN C15 [get_ports {seg_out[6]}]
set_property PACKAGE_PIN E13 [get_ports {seg_out[7]}]



set_property PACKAGE_PIN K17 [get_ports onehz]
set_property IOSTANDARD LVCMOS33 [get_ports onehz]

set_property IOSTANDARD LVCMOS33 [get_ports audio]
set_property IOSTANDARD LVCMOS33 [get_ports button]
set_property IOSTANDARD LVCMOS33 [get_ports sys_CLK]
set_property PACKAGE_PIN A19 [get_ports audio]
set_property PACKAGE_PIN Y18 [get_ports sys_CLK]
set_property PACKAGE_PIN P2 [get_ports button]

set_property IOSTANDARD LVCMOS33 [get_ports sp]
set_property PACKAGE_PIN P2 [get_ports sp]

set_property IOSTANDARD LVCMOS33 [get_ports {q2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q3[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q3[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q3[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q3[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q4[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q4[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q4[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q4[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q5[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q5[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q5[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q5[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q6[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q6[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q6[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q6[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q7[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q7[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q7[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q7[0]}]
set_property PACKAGE_PIN E21 [get_ports {q2[3]}]
set_property PACKAGE_PIN A21 [get_ports {q2[0]}]
set_property PACKAGE_PIN E22 [get_ports {q2[1]}]
set_property PACKAGE_PIN D22 [get_ports {q2[2]}]
set_property PACKAGE_PIN D21 [get_ports {q3[0]}]
set_property PACKAGE_PIN G21 [get_ports {q3[1]}]
set_property PACKAGE_PIN G22 [get_ports {q3[2]}]
set_property PACKAGE_PIN F21 [get_ports {q3[3]}]
set_property PACKAGE_PIN J17 [get_ports {q4[0]}]
set_property PACKAGE_PIN L14 [get_ports {q4[1]}]
set_property PACKAGE_PIN L15 [get_ports {q4[2]}]
set_property PACKAGE_PIN L16 [get_ports {q4[3]}]
set_property PACKAGE_PIN K16 [get_ports {q5[0]}]
set_property PACKAGE_PIN M15 [get_ports {q5[1]}]
set_property PACKAGE_PIN M16 [get_ports {q5[2]}]
set_property PACKAGE_PIN M17 [get_ports {q5[3]}]
set_property PACKAGE_PIN N19 [get_ports {q6[0]}]
set_property PACKAGE_PIN N20 [get_ports {q6[1]}]
set_property PACKAGE_PIN M20 [get_ports {q6[2]}]
set_property PACKAGE_PIN K13 [get_ports {q6[3]}]
set_property PACKAGE_PIN K14 [get_ports {q7[0]}]
set_property PACKAGE_PIN M13 [get_ports {q7[1]}]
set_property PACKAGE_PIN L13 [get_ports {q7[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports runstate]
set_property PACKAGE_PIN K17 [get_ports runstate]
set_property PULLDOWN true [get_ports {q7[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seconds[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seconds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seconds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seconds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seconds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seconds[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seconds[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seconds[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seconds[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seconds[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seconds[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seconds[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seconds[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seconds[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seconds[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seconds[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seconds[16]}]
set_property PACKAGE_PIN A21 [get_ports {seconds[0]}]
set_property PACKAGE_PIN E22 [get_ports {seconds[1]}]
set_property PACKAGE_PIN D22 [get_ports {seconds[2]}]
set_property PACKAGE_PIN E21 [get_ports {seconds[3]}]
set_property PACKAGE_PIN D21 [get_ports {seconds[4]}]
set_property PACKAGE_PIN G21 [get_ports {seconds[5]}]
set_property PACKAGE_PIN G22 [get_ports {seconds[6]}]
set_property PACKAGE_PIN F21 [get_ports {seconds[7]}]
set_property PACKAGE_PIN J17 [get_ports {seconds[8]}]
set_property PACKAGE_PIN L14 [get_ports {seconds[9]}]
set_property PACKAGE_PIN L15 [get_ports {seconds[10]}]
set_property PACKAGE_PIN L16 [get_ports {seconds[11]}]
set_property PACKAGE_PIN K16 [get_ports {seconds[12]}]
set_property PACKAGE_PIN M15 [get_ports {seconds[13]}]
set_property PACKAGE_PIN M16 [get_ports {seconds[14]}]
set_property PACKAGE_PIN M17 [get_ports {seconds[15]}]
set_property PACKAGE_PIN N19 [get_ports {seconds[16]}]

set_property IOSTANDARD LVCMOS33 [get_ports btn]
set_property PACKAGE_PIN P2 [get_ports btn]

set_property IOSTANDARD LVCMOS33 [get_ports change_btn]
set_property IOSTANDARD LVCMOS33 [get_ports mode_btn]
set_property IOSTANDARD LVCMOS33 [get_ports set_btn]
set_property IOSTANDARD LVCMOS33 [get_ports toggle_btn]
set_property PACKAGE_PIN P1 [get_ports change_btn]
set_property PACKAGE_PIN P5 [get_ports mode_btn]
set_property PACKAGE_PIN P4 [get_ports set_btn]
set_property PACKAGE_PIN P2 [get_ports toggle_btn]

set_property PACKAGE_PIN L13 [get_ports al_en]
set_property PACKAGE_PIN M13 [get_ports clk_en]
set_property PACKAGE_PIN K14 [get_ports sw_en]
set_property IOSTANDARD LVCMOS33 [get_ports al_en]
set_property IOSTANDARD LVCMOS33 [get_ports clk_en]
set_property IOSTANDARD LVCMOS33 [get_ports sw_en]

set_property PACKAGE_PIN M2 [get_ports {col[3]}]
set_property PACKAGE_PIN K6 [get_ports {col[2]}]
set_property PACKAGE_PIN J6 [get_ports {col[1]}]
set_property PACKAGE_PIN L5 [get_ports {col[0]}]

set_property PACKAGE_PIN K4 [get_ports {row[3]}]
set_property PACKAGE_PIN J4 [get_ports {row[2]}]
set_property PACKAGE_PIN L3 [get_ports {row[1]}]
set_property PACKAGE_PIN K3 [get_ports {row[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {col[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports keyboard_en]
set_property PACKAGE_PIN M20 [get_ports keyboard_en]

set_property IOSTANDARD LVCMOS33 [get_ports {alr_cur_set[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {alr_cur_set[0]}]
set_property PACKAGE_PIN A21 [get_ports {alr_cur_set[1]}]
set_property PACKAGE_PIN E22 [get_ports {alr_cur_set[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {alr_music_dbg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {alr_music_dbg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {alr_music_dbg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {alr_music_dbg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {alr_music_dbg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {alr_music_dbg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {alr_music_dbg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {alr_music_dbg[7]}]
set_property PACKAGE_PIN D22 [get_ports {alr_music_dbg[0]}]
set_property PACKAGE_PIN E21 [get_ports {alr_music_dbg[1]}]
set_property PACKAGE_PIN D21 [get_ports {alr_music_dbg[2]}]
set_property PACKAGE_PIN G21 [get_ports {alr_music_dbg[3]}]
set_property PACKAGE_PIN G22 [get_ports {alr_music_dbg[4]}]
set_property PACKAGE_PIN F21 [get_ports {alr_music_dbg[5]}]
set_property PACKAGE_PIN J17 [get_ports {alr_music_dbg[6]}]
set_property PACKAGE_PIN L14 [get_ports {alr_music_dbg[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {digit_dbg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_dbg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_dbg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_dbg[3]}]
set_property PACKAGE_PIN L15 [get_ports {digit_dbg[0]}]
set_property PACKAGE_PIN L16 [get_ports {digit_dbg[1]}]
set_property PACKAGE_PIN K16 [get_ports {digit_dbg[2]}]
set_property PACKAGE_PIN M15 [get_ports {digit_dbg[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports alarm_light]
set_property PACKAGE_PIN N19 [get_ports alarm_light]

set_property PACKAGE_PIN K13 [get_ports cd_en]
set_property IOSTANDARD LVCMOS33 [get_ports cd_en]
